---

- name: APT | Add DotDeb repository
  apt_repository: repo='{{ item }}' state=present
  with_items:
    - deb http://packages.dotdeb.org {{ with_dotdeb }} all
    - deb-src http://packages.dotdeb.org {{ with_dotdeb }} all
  tags: dotdeb
  when: with_dotdeb

- name: php5 is installed
  action: apt pkg={{ item }} state=present
  with_items: php_packages

- name: Copy date.ini fpm
  copy: src=date.ini dest=/etc/php5/fpm/conf.d/00-date.ini group=root owner=root

- name: Copy date.ini cli
  copy: src=date.ini dest=/etc/php5/cli/conf.d/00-date.ini group=root owner=root

- name: Start php-fpm service
  service: name="php5-fpm" state=started enabled=true
  ignore_errors: yes
